{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name | default (printf "%s-cert" .Release.Name) }}
  namespace: {{ .Values.namespaceOverride | default (include "common.names.namespace" .) | quote }}
  labels:
    {{- include "certificate-cert-manager.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
  dnsNames:
    {{- toYaml .Values.certificate.dnsNames | nindent 4 }}
  privateKey:
    algorithm: {{ .Values.certificate.privateKey.algorithm }}
    size: {{ .Values.certificate.privateKey.size }}
{{- end }}
