apiVersion: batch/v1
kind: Job
metadata:
  name: pgm-app
  namespace: {{ .Values.name }}-{{ .Values.namespace }}
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: default
      initContainers:
        - name: ensure-db
          image: bitnami/postgresql:14.17.0
          command: ["/bin/sh"]
          args:
            - -c
            - |
              psql -h {{ .Values.db.host }} -p {{ .Values.db.port }} -U {{ .Values.db.user }} -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='{{ .Values.db.dbname}}'" | grep -q 1 || \
              createdb -h {{ .Values.db.host }} -p {{ .Values.db.port }} -U {{ .Values.db.user }} {{ .Values.db.dbname}}
          env:
            - name: PGPASSWORD
              value: "{{ .Values.db.password }}"
        - name: clone-migrations
          image: alpine/git
          command: ["/bin/sh"]
          args:
            - -c
            - |
              git clone --branch {{ .Values.migrations.gitRef }} https://{{ .Values.migrations.gitUsername }}:${GIT_TOKEN}@{{ .Values.migrations.gitHost }}{{ .Values.migrations.gitPath }} /flyway/sql/migrations
          env:
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-readonly-user-token-secret
                  key: token
          volumeMounts:
            - name: migration-volume
              mountPath: /flyway/sql/migrations

      containers:
        - name: flyway
          image: {{ .Values.image }}
          command: [ "flyway" ]
          args:
            - -url=jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.dbname}}?user={{ .Values.db.user }}&password={{ .Values.db.password }}
            - -locations=filesystem:/flyway/sql/migrations
            - migrate
          volumeMounts:
            - name: migration-volume
              mountPath: /flyway/sql/migrations
      volumes:
        - name: migration-volume
          emptyDir: {}